/*
try {
    let x = y + 10;
    console.log(x);
} catch (erro) {
    console.log(erro);
    console.log(erro.name);
}
*/

try {
    let num = 1;
    num.toUpperCase();
} catch (erro) {
    console.log(erro);
    console.log(erro.name);
}